import { query } from "@anthropic-ai/claude-agent-sdk";
import { createLogger } from "@journeyman/core";
import { logSdkMessage } from "../utils/sdk-logger.ts";
import { resolveSession } from "../utils/session.ts";
import type { CheckoutEntry, CheckoutRepoOptions, CheckoutRepoResult } from "@journeyman/core";

const log = createLogger("claude:checkout-repo");

export type { CheckoutEntry, CheckoutRepoOptions, CheckoutRepoResult };

const OUTPUT_SCHEMA = {
  type: "object",
  properties: {
    newBranch: { type: "string" },
    repos: {
      type: "array",
      items: {
        type: "object",
        properties: {
          folderName: { type: "string" },
          dirPath: { type: "string" },
          baseBranch: { type: "string" },
          newBranch: { type: "string" },
          success: { type: "boolean" },
          error: { type: "string" },
        },
        required: ["folderName", "dirPath", "baseBranch", "newBranch", "success"],
      },
    },
    error: { type: "string" },
  },
  required: ["newBranch", "repos"],
} as const;

function normalizeEntries(opts: CheckoutRepoOptions): CheckoutEntry[] {
  const raw = Array.isArray(opts.repos) ? opts.repos : [opts.repos];
  return raw.map((r) =>
    typeof r === "string" ? { dirPath: r, branch: opts.branch ?? "main" } : r
  );
}

function buildPrompt(
  entries: CheckoutEntry[],
  ticket: CheckoutRepoOptions["ticket"],
): string {
  const steps = entries
    .map(({ dirPath, branch }) => `  - ${dirPath} → baseBranch: ${branch}`)
    .join("\n");

  const namingRule = ticket
    ? [
        "BRANCH NAMING (ticket provided):",
        `  Format: "{id-lowercased}/{2-4-word-slug}_{unix-seconds}"`,
        `  Ticket id: ${ticket.id}`,
        `  Ticket title: ${ticket.title}`,
        `  Slug: lowercase ASCII, hyphen-separated, 2-4 meaningful words from the title`,
        `         (strip stopwords like "the", "a", "an", "on", "for", "to", "of", "and").`,
        `  Example: id "EV-12345", title "Fix header alignment bug on checkout page"`,
        `           → "ev-12345/fix-header-alignment_1713542400"`,
      ].join("\n")
    : [
        "BRANCH NAMING (no ticket):",
        `  Format: "{animal-themed-slug}_{unix-seconds}"`,
        `  Slug: lowercase ASCII, hyphen-separated, 2-3 words containing one animal name`,
        `         (e.g. "curious-otter-sprint", "swift-falcon-work").`,
      ].join("\n");

  return [
    "You will sync local repos to origin, then create ONE new feature branch used across all repos.",
    "",
    namingRule,
    "",
    "  - Before touching any repo, run `date +%s` ONCE to get the current unix-seconds timestamp.",
    "  - Use that single timestamp value in the branch name for ALL repos. Do NOT re-run `date` inside the per-repo loop.",
    "  - The EXACT same branch name must be used for every repo.",
    "",
    "PER-REPO STEPS (run in order for each repo):",
    "  1. git -C <dirPath> fetch origin",
    "  2. git -C <dirPath> stash --include-untracked   (discard local changes)",
    "  3. git -C <dirPath> checkout <baseBranch>",
    "  4. git -C <dirPath> pull origin <baseBranch>",
    "  5. git -C <dirPath> reset --hard origin/<baseBranch>",
    "  6. git -C <dirPath> clean -fd",
    "  7. git -C <dirPath> checkout -b <newBranch>",
    "",
    "Repos:",
    steps,
    "",
    "Return JSON with:",
    "  - newBranch (top-level): the generated branch name used for all repos",
    "  - repos[]: { folderName, dirPath, baseBranch, newBranch, success, error? }",
    "  - error (top-level, optional): set only if everything failed before per-repo work started",
    "Capture per-repo errors in repos[].error and set success=false for that repo.",
  ].join("\n");
}

/**
 * Hard-resets each repo's base branch to match origin, then creates ONE new
 * feature branch (used across all repos). Branch name is generated by Claude
 * from ticket details when provided, or as an animal-themed fallback.
 *
 * @param opts - Repos, base branch, and optional ticket driving the branch name.
 * @returns A CheckoutRepoResult with the generated newBranch and per-repo details.
 *
 * @example
 * ```ts
 * const result = await checkoutRepo({
 *   repos: [
 *     { dirPath: "/projects/api", branch: "main" },
 *     { dirPath: "/projects/web", branch: "main" },
 *   ],
 *   ticket: { id: "EV-12345", title: "Fix header alignment on checkout" },
 * });
 * console.log(result.newBranch); // e.g. "ev-12345/fix-header-alignment_1713542400"
 * ```
 */
export async function checkoutRepo(opts: CheckoutRepoOptions): Promise<CheckoutRepoResult> {
  const entries = normalizeEntries(opts);
  const { sessionId, queryOption } = resolveSession(opts.sessionId);
  log.info(
    { sessionId, repoCount: entries.length, ticketId: opts.ticket?.id },
    "checkoutRepo start",
  );
  if (entries.length === 0) {
    log.warn({ sessionId }, "checkoutRepo called with no repos");
    return { repos: [], newBranch: "", sessionId };
  }
  const controller = opts.signal
    ? (() => {
        const ac = new AbortController();
        if (opts.signal!.aborted) ac.abort(opts.signal!.reason);
        else opts.signal!.addEventListener("abort", () => ac.abort(opts.signal!.reason), { once: true });
        return ac;
      })()
    : undefined;
  let output: CheckoutRepoResult = { repos: [], newBranch: "", sessionId };

  for await (const msg of query({
    prompt: buildPrompt(entries, opts.ticket),
    options: {
      tools: ["Bash"],
      allowedTools: ["Bash"],
      permissionMode: "bypassPermissions",
      allowDangerouslySkipPermissions: true,
      maxTurns: 40,
      settingSources: [],
      settings: { allowedMcpServers: [] },
      outputFormat: { type: "json_schema", schema: OUTPUT_SCHEMA },
      ...(controller !== undefined ? { abortController: controller } : {}),
      ...queryOption,
    },
  })) {
    logSdkMessage(msg);
    if (msg.type === "result") {
      if (msg.subtype !== "success") {
        const error = (msg as any).errors?.[0] ?? msg.subtype;
        log.error({ sessionId, error }, "checkoutRepo failed");
        return { repos: [], newBranch: "", error, sessionId };
      }
      output = { ...(msg.structured_output as CheckoutRepoResult), sessionId };
    }
  }

  log.info(
    {
      sessionId,
      newBranch: output.newBranch,
      successCount: output.repos.filter((r) => r.success).length,
      failureCount: output.repos.filter((r) => !r.success).length,
    },
    "checkoutRepo done",
  );
  return output;
}

// Run directly: npx tsx checkout-repo.ts
if (import.meta.url === `file://${process.argv[1]}`) {
  const result = await checkoutRepo({
    repos: [
      { dirPath: "/Users/admin/data/workspace/my-api", branch: "main" },
      { dirPath: "/Users/admin/data/workspace/my-web", branch: "main" },
    ],
    ticket: { id: "EV-12345", title: "Fix header alignment on checkout" },
  });

  process.stdout.write(JSON.stringify(result, null, 2) + "\n");
}
