# Minimal Conductor standalone config for local dev.
conductor.db.type=postgres
spring.datasource.url=jdbc:postgresql://postgres:5432/journeyman
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.hikari.maximum-pool-size=10

conductor.queue.type=redis_standalone
conductor.redis.hosts=redis:6379:us-east-1
conductor.redis.workflowNamespacePrefix=conductor
conductor.redis.queueNamespacePrefix=conductor

conductor.app.workflowOffsetTimeout=PT5S
